[package]
name = "gedcomx_date"
version = "0.0.1"
authors = ["Nicolas Barbotte <nicolas@barbotte.net>"]

description = "Gedcomx Date Parser"

license = "MIT"
readme = "README.md"

[dependencies]
nom = "4.1.1"

clippy = {version = "~0.0.46", optional = true}

[features]
default = []
dev = ["clippy"]
bench = []
